### ISSUE TITLE
Cannot build image using buildpacks regardless Python runtime

### ISSUE THREAD

**Issue by punkerpunker** [heroku/builder#241]
Trying to build a simple python image, but constantly get an error: `Requested runtime is not available for this stack` regardless runtime version specified. 

```
[glebvazhenin@datascience10.mlan backend]$ pack build --builder heroku/buildpacks:20 dockerio.badoo.com/ds/ant-kf:0.0.2
20: Pulling from heroku/buildpacks
Digest: sha256:b08d9db38bd21ad7f3a25095aebb92c997ab8daf2c0c7c4d29d13bb67024f901
Status: Image is up to date for heroku/buildpacks:20
20: Pulling from heroku/pack
Digest: sha256:240e93d72e8a7d4f7ce55f67ea917464a1f1ee7151b119058a37a25b5b2bfaf3
Status: Image is up to date for heroku/pack:20
===> ANALYZING
Previous image with name "dockerio.badoo.com/ds/ant-kf:0.0.2" not found
===> DETECTING
heroku/python   0.3.1
heroku/procfile 1.0.1
===> RESTORING
===> BUILDING
-----> No Python version was specified. Using the buildpack default: python-3.10.4
       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
 !     Requested runtime (python-3.10.4) is not available for this stack (heroku-20).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

I am using the newest version of `buildpacks:20` image. Same command was working a couple of days ago, not sure if I am doing something wrong, or some recent change in `buildpacks:20` caused this issue. Will appreciate any help, thank you!

**Comment by edmorley** [comment]
This works for me now:

```

```

I would imagine this was due to a transient network issue that caused the downloading of the Python archive to fail. 

The Python buildpack in the `heroku/buildpacks:20` builder is not a native CNB, but a shimmed version of the classic CNB, so based on an older codebase that doesn't have great UX for this case:
https://github.com/heroku/heroku-buildpack-python/blob/2149725b17bb95cbaf065809f09cd49eb3cfd1c5/bin/steps/python#L138-L142

In general, other than the JVM/Java and Node buildpacks in this builder, everything else is a WIP and may change at any time, and should not be replied upon for production usage.

The new in-progress native Python CNB I am working on has finer grained error messages that will make debugging this kind of scenario much easier at least :-)
