### ISSUE TITLE
Regression: processes is not parseable in metadata.toml

### ISSUE THREAD

**Issue by ipmb** [heroku/builder#295]
I'm using the latest `pack` to build my images. Previously `/layers/config/metadata.toml` defined processes like this:

```
[[processes]]
  type = "release"
  command = "manage.py migrate --noinput"
  direct = false
  buildpack-id = "heroku/python"

[[processes]]
  type = "web"
  command = "manage.py gunicorn --logger-class=ll.apps.utils.log.GunicornJsonLogger --access-logfile=- --timeout=10 --bind=0.0.0.0:$PORT --forwarded-allow-ips '*'"
  direct = false
  buildpack-id = "heroku/python"
```

The latest release is now dumping them out like this which I assume is not intended:

```
processes = ["type = \"release\"\ncommand = \"manage.py migrate --noinput\"\nargs = []\ndirect = false\nbuildpack-id = \"heroku/python\"\n", "type = \"web\"\ncommand = \"manage.py gunicorn --logger-class=ll.apps.utils.log.GunicornJsonLogger --access-logfile=- --timeout=10 --bind=0.0.0.0:$PORT --forwarded-allow-ips '*'\"\nargs = []\ndirect = false\nbuildpack-id = \"heroku/python\"\n"]
```

This breaks any code that was parsing `metadata.toml` to get the processes used by the image.

**Comment by edmorley** [comment]
Hi! Thank you for filing.

The `lifecycle` binary in the builder image was just updated in #294 (release notes and diff links in the PR description). 

With the latest version of the builder I get:

```
$ mkdir testcase && cd $_
$ touch requirements.txt
$ echo 'web: foo' > Procfile
$ pack build --builder heroku/builder-classic:22 testapp
22: Pulling from heroku/builder-classic
...
Successfully built image testapp
$ docker run --rm -it --platform linux/amd64 --entrypoint launcher testapp cat /layers/config/metadata.toml
processes = ["type = \"web\"\ncommand = \"foo\"\nargs = []\ndirect = false\nbuildpack-id = \"heroku/procfile\"\n"]
buildpack-default-process-type = "web"

[[buildpacks]]
  id = "heroku/python"
  version = "0.0.0"
  api = "0.4"

[[buildpacks]]
  id = "heroku/procfile"
  version = "2.0.0"
  api = "0.8"
  homepage = "https://github.com/heroku/procfile-cnb"
```

Whereas using the previous builder image (which was using lifecycle 0.14.1), I get:

```
$ docker run --rm -it --platform linux/amd64 --entrypoint launcher testapp-previous cat /layers/config/metadata.toml
buildpack-default-process-type = "web"

[[buildpacks]]
  api = "0.4"
  id = "heroku/python"
  version = "0.0.0"

[[buildpacks]]
  api = "0.8"
  homepage = "https://github.com/heroku/procfile-cnb"
  id = "heroku/procfile"
  version = "2.0.0"

[[processes]]
  type = "web"
  command = "foo"
  direct = false
  buildpack-id = "heroku/procfile"
```

I also tried using the latest builder along with `--lifecycle-image buildpacksio/lifecycle:0.14.3` in order to try and reduce the regression range (given there were multiple versions in the range, and not just 0.15.0). However, I first ran into buildpacks/pack/issues/1540, and then even after marking the builder as untrusted (to force it to use the specified lifecycle image), I got this error instead:

```
===> EXPORTING
[exporter] ERROR: failed to export: read build metadata: toml: type mismatch for launch.Process: expected table but found string
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 62
```

It seems that:
- When `--lifecycle-image` is used, it only overrides the lifecycle for the analysis, restore, and export phases, and the default lifecycle that ships with the builder is still used for the remaining phases.
- lifecycle 0.14.3 is not forwards compatible with the metadata written by lifecycle 0.15.0.

I'm presuming this might be fallout from one of these changes (cc @jabrown85):
https://github.com/buildpacks/lifecycle/pull/889
https://github.com/buildpacks/lifecycle/pull/900

@ipmb Would you be up for filing an issue upstream about this?
https://github.com/buildpacks/lifecycle/issues

**Comment by edmorley** [comment]
Thank you for filing the upstream issue:
https://github.com/buildpacks/lifecycle/issues/945

I've opened a PR to revert the lifecycle upgrade for now:
https://github.com/heroku/builder/pull/296
